server {
    listen 80;
    server_name _;

    # Fichiers statiques React
    root /usr/share/nginx/html;
    index index.html;

    # SPA — toutes les routes non-API renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy vers Gunicorn (back-end Django)
    location /api/v1/ {
        proxy_pass http://back:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Admin Django
    location /admin/ {
        proxy_pass http://back:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Fichiers statiques Django (collectstatic)
    location /static/ {
        proxy_pass http://back:8000;
    }

    # HTTPS — à activer après Certbot
    # listen 443 ssl;
    # ssl_certificate /etc/letsencrypt/live/votre-domaine.fr/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/votre-domaine.fr/privkey.pem;
    # include /etc/letsencrypt/options-ssl-nginx.conf;
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
