# Generated by Django 4.2.16 on 2026-03-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_mealplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['user__username']},
        ),
    ]
